# Generated by Django 3.2.6 on 2021-08-28 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_Name', models.CharField(max_length=100)),
                ('Teacher_Address', models.TextField()),
                ('Teacher_Joining_Date', models.DateTimeField(auto_now_add=True)),
                ('School_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS_CRUD.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=100)),
                ('Student_Address', models.TextField()),
                ('Student_Roll_No', models.IntegerField()),
                ('Student_File', models.FileField(upload_to='')),
                ('School_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS_CRUD.school')),
                ('Teacher_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS_CRUD.teacher')),
            ],
        ),
    ]
