# Generated by Django 3.2.6 on 2021-08-29 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS_CRUD', '0004_alter_student_student_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='School_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SMS_CRUD.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_Roll_No',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Teacher_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SMS_CRUD.teacher'),
        ),
    ]
