# Generated by Django 3.2.6 on 2021-08-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS_CRUD', '0005_auto_20210829_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_File',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
